seed: 12345
canvas_size: [384, 384]
padding: 5
bg_color: "#7f7f7f"
colors: # Lists, so they can be sorted. Keys should be unique.
  - red: "#ff0000"
  - yellow: "#ffff00"
  - green: "#00ff00"
  - cyan: "#00ffff"
  - blue: "#0000ff"
  - magenta: "#ff00ff"
sizes:
  - small: 10
  - large: 25
size_noise: 3
h_sigma: 0.01
s_sigma: 0.2
v_sigma: 0.2
background_knowledge: minimal_bg.pl
